# Generated by Django 5.1 on 2024-08-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_aluno_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='imagem',
            new_name='image',
        ),
    ]
